version: '3.4'

services:
  fiep_api:
    image: ${DOCKER_REGISTRY-}fiepapi
    build:
      context: .
      dockerfile: FIEP_API/Dockerfile
    depends_on:
      - mssql
      - redis
  mssql:
    container_name: mssql
    #image: "microsoft/mssql-server-linux:latest"
    build:
      context: .
      dockerfile: MSSQL/Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=feip_str0ngpwd
      - MSSQL_PID=Express
    ports:
      - "8089:1433"
    volumes:
     - /MSSQL/data:/var/opt/mssql - /var/opt/mssql/data

  redis:
    container_name: redis
    build:
      context: .
      dockerfile: Redis/Dockerfile
    #image: "redis:alpine"
    #command: redis-server --requirepass feip_str0ngpwd
    ports:
     - "6379:6379"
    volumes:
     - $PWD/Redis/data:/var/lib/redis
    environment:
     - REDIS_REPLICATION_MODE=master