version: '3.4'

services:
  fiep_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - GOOGLE_APPLICATION_CREDENTIALS=/src/FIEP_API/keys/fiep-86d04-firebase-adminsdk-davhp-ac304e11a7.json
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro